class InstrumentId:
    def __init__(self, symbol: str, venue: str) -> None: ...
    @staticmethod
    def from_str(value: str) -> InstrumentId: ...
    @property
    def value(self) -> str: ...

class ClientId:
    def __init__(self, value: str) -> None: ...

class TraderId:
    def __init__(self, value: str) -> None: ...
